blueprint:
  name: Bathroom Humidity Ventilation v2.6
  description: >
    Data-driven ventilation advice with volume control, configurable logging levels
    (NONE/DEBUG/TRACE), and nag limits, based on absolute humidity and temperature.
    Uses an input_datetime helper to rate-limit announcements based on the last
    *spoken* message (not last automation trigger).
  domain: automation

  input:
    house_mode_sensor:
      name: House master mode sensor
      default: sensor.house_master_mode
      selector:
        entity:
          domain: sensor

    sensor_abs_inside:
      name: Bathroom absolute humidity
      default: sensor.bad_absolute_humidity
      selector:
        entity:
          domain: sensor

    sensor_rh_inside:
      name: Bathroom relative humidity
      default: sensor.bad_klimasensor_humidity
      selector:
        entity:
          domain: sensor

    sensor_abs_outside:
      name: Outside absolute humidity
      default: sensor.balkon_absolute_humidity
      selector:
        entity:
          domain: sensor

    sensor_temp_inside:
      name: Bathroom temperature
      default: sensor.bad_klimasensor_temperature
      selector:
        entity:
          domain: sensor

    window_contact:
      name: Bathroom window contact
      default: binary_sensor.bad_fenster_contact
      selector:
        entity:
          domain: binary_sensor

    # NEW: helper for rate-limiting (stores timestamp of last spoken TTS)
    last_tts_helper:
      name: Last spoken timestamp helper
      description: input_datetime helper that stores when the last announcement was spoken.
      selector:
        entity:
          domain: input_datetime

    announce_interval_mins:
      name: Minimum minutes between announcements
      description: Applies to both OPEN and CLOSE hints (helper-based).
      default: 10
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: "min"

    # TTS helper script + optional overrides
    tts_script:
      name: TTS helper script
      description: Script created from the TTS Speak Helper blueprint
      selector:
        entity:
          domain: script

    tts_media_player:
      name: Media player override (optional)
      description: Entity ID string; leave empty to use TTS helper default
      default: ""
      selector:
        text: {}

    tts_language:
      name: TTS language override (optional)
      description: Leave empty to use the TTS helper's default
      default: ""
      selector:
        text: {}

    tts_volume:
      name: TTS volume override (optional)
      description: Leave empty to use the TTS helper's default
      default: ""
      selector:
        text: {}

    tts_message_open:
      name: TTS message when window is closed (open hint)
      description: Jinja templates allowed; defaults to humidity + open request
      default: >-
        Hohe Luftfeuchtigkeit ({{ rh_inside | round(0) }}%). Bitte Bad Fenster öffnen.
      selector:
        text:
          multiline: true

    tts_message_close_cold:
      name: TTS message when too cold (close hint)
      description: Default cold-protection close request
      default: Achtung, Kälteschutz! Bad Fenster schließen.
      selector:
        text:
          multiline: true

    tts_message_close_normal:
      name: TTS message when normalized (close hint)
      description: Default close request after humidity normalized
      default: Luftwerte normalisiert. Bad Fenster schließen.
      selector:
        text:
          multiline: true

    thresh_rh_open:
      name: RH open threshold (%)
      default: 77
      selector:
        number:
          min: 40
          max: 100
          step: 1
          unit_of_measurement: "%"

    thresh_abs_open:
      name: Absolute humidity open threshold (g/m³)
      default: 11.5
      selector:
        number:
          min: 5
          max: 30
          step: 0.1

    thresh_rh_close:
      name: RH close threshold (%)
      default: 68
      selector:
        number:
          min: 30
          max: 100
          step: 1
          unit_of_measurement: "%"

    thresh_abs_close:
      name: Absolute humidity close threshold (g/m³)
      default: 10.8
      selector:
        number:
          min: 5
          max: 30
          step: 0.1

    min_delta:
      name: Minimum absolute humidity delta (g/m³)
      default: 1.5
      selector:
        number:
          min: 0.1
          max: 10
          step: 0.1

    min_temp:
      name: Minimum safe temperature (°C)
      default: 16.5
      selector:
        number:
          min: 5
          max: 30
          step: 0.5

    min_open_time:
      name: Minimum open time before close hint (min)
      default: 15
      selector:
        number:
          min: 1
          max: 120
          step: 1

    log_level:
      name: Logging level
      description: NONE = no logs, DEBUG = actionable outcomes only, TRACE = all outcomes including NOOP
      default: DEBUG
      selector:
        select:
          options:
            - NONE
            - DEBUG
            - TRACE

triggers:
  - trigger: state
    entity_id:
      - !input sensor_abs_inside
      - !input sensor_rh_inside
      - !input sensor_abs_outside
      - !input sensor_temp_inside
      - !input window_contact

conditions:
  - condition: state
    entity_id: !input house_mode_sensor
    state:
      - Morning
      - Day
      - Evening

actions:
  - variables:
      log_level: !input log_level

      abs_inside_entity: !input sensor_abs_inside
      abs_outside_entity: !input sensor_abs_outside
      rh_inside_entity: !input sensor_rh_inside
      temp_inside_entity: !input sensor_temp_inside
      window_entity: !input window_contact

      # NEW: helper + interval
      last_tts_entity: !input last_tts_helper
      announce_interval_mins: !input announce_interval_mins

      abs_inside: "{{ states(abs_inside_entity) | float(0) }}"
      abs_outside: "{{ states(abs_outside_entity) | float(0) }}"
      rh_inside: "{{ states(rh_inside_entity) | float(0) }}"
      temp_inside: "{{ states(temp_inside_entity) | float(0) }}"
      window_state: "{{ states(window_entity) }}"
      window_last_changed: "{{ states[window_entity].last_changed }}"

      time_open_mins: >-
        {% if window_last_changed %}
          {{ (((as_timestamp(now()) - as_timestamp(window_last_changed)) / 60)) | float(0) }}
        {% else %}
          0
        {% endif %}

      # NEW: mins since last *spoken* message (helper-based)
      last_tts_ts: >-
        {% set s = states(last_tts_entity) %}
        {% if s in ['unknown','unavailable','none',''] %}
          0
        {% else %}
          {{ as_timestamp(s) | float(0) }}
        {% endif %}

      mins_since_last_announce: >-
        {% if last_tts_ts == 0 %}
          999999
        {% else %}
          {{ ((as_timestamp(now()) - last_tts_ts) / 60) | float(0) }}
        {% endif %}

      thresh_rh_open: !input thresh_rh_open
      thresh_abs_open: !input thresh_abs_open
      thresh_rh_close: !input thresh_rh_close
      thresh_abs_close: !input thresh_abs_close
      min_delta: !input min_delta
      min_temp: !input min_temp
      min_open_time: !input min_open_time

      delta: "{{ (abs_inside - abs_outside) | round(2) }}"

      sensors_ok: >-
        {{
          states(abs_inside_entity) not in ['unknown','unavailable']
          and states(abs_outside_entity) not in ['unknown','unavailable']
          and states(rh_inside_entity) not in ['unknown','unavailable']
          and states(temp_inside_entity) not in ['unknown','unavailable']
          and window_state not in ['unknown','unavailable']
        }}

      is_shower_zone: "{{ rh_inside > thresh_rh_open or abs_inside > thresh_abs_open }}"
      is_physics_good: "{{ (abs_inside - abs_outside) >= min_delta }}"
      is_temp_safe: "{{ temp_inside > min_temp }}"

      # TTS helper + raw override values (may be empty)
      tts_script: !input tts_script
      tts_media_player_in: !input tts_media_player
      tts_language_in: !input tts_language
      tts_volume_in: !input tts_volume
      tts_message_open: !input tts_message_open
      tts_message_close_cold: !input tts_message_close_cold
      tts_message_close_normal: !input tts_message_close_normal

      # --- Compact decision & logging (heating-style) ---
      outcome: >-
        {% if not sensors_ok %}
          NOOP
        {% elif window_state == 'off'
              and is_shower_zone
              and is_physics_good
              and is_temp_safe
              and mins_since_last_announce >= announce_interval_mins %}
          OPEN_HINT
        {% elif window_state == 'on'
              and mins_since_last_announce >= announce_interval_mins
              and (temp_inside < min_temp
                   or (time_open_mins >= min_open_time
                       and (rh_inside <= thresh_rh_close
                            or abs_inside <= thresh_abs_close
                            or delta < 0.5))) %}
          CLOSE_HINT
        {% else %}
          NOOP
        {% endif %}

      outcome_reason: >-
        {% if not sensors_ok %}
          Sensors not available
        {% elif outcome == 'OPEN_HINT' %}
          High humidity + outside drier + temp safe
        {% elif outcome == 'CLOSE_HINT' and temp_inside < min_temp %}
          Cold protection
        {% elif outcome == 'CLOSE_HINT' %}
          Open long enough + normalized
        {% else %}
          No action
        {% endif %}

      # Determine humidity status with reason (OK or NOT OK) regardless of action taken
      humidity_status: >-
        {% if not sensors_ok %}
          UNKNOWN (sensors unavailable)
        {% elif window_state == 'off' and is_shower_zone %}
          {% if rh_inside > thresh_rh_open %}
            High: {{ rh_inside | round(0) }}% > {{ thresh_rh_open }}% threshold
          {% elif abs_inside > thresh_abs_open %}
            High: {{ abs_inside | round(1) }} g/m³ > {{ thresh_abs_open }} threshold
          {% else %}
            High: in shower zone
          {% endif %}
        {% elif window_state == 'on' and (rh_inside <= thresh_rh_close or abs_inside <= thresh_abs_close or delta < 0.5) %}
          {% if rh_inside <= thresh_rh_close %}
            Normalized: {{ rh_inside | round(0) }}% ≤ {{ thresh_rh_close }}% threshold
          {% elif abs_inside <= thresh_abs_close %}
            Normalized: {{ abs_inside | round(1) }} g/m³ ≤ {{ thresh_abs_close }} threshold
          {% elif delta < 0.5 %}
            Normalized: delta {{ delta | round(1) }} < 0.5 g/m³
          {% else %}
            Normalized
          {% endif %}
        {% elif window_state == 'off' and not is_shower_zone %}
          OK: {{ rh_inside | round(0) }}% ≤ {{ thresh_rh_open }}% and {{ abs_inside | round(1) }} ≤ {{ thresh_abs_open }} g/m³
        {% elif window_state == 'on' and not (rh_inside <= thresh_rh_close or abs_inside <= thresh_abs_close or delta < 0.5) %}
          {% if rh_inside > thresh_rh_close %}
            Still high: {{ rh_inside | round(0) }}% > {{ thresh_rh_close }}% threshold
          {% elif abs_inside > thresh_abs_close %}
            Still high: {{ abs_inside | round(1) }} g/m³ > {{ thresh_abs_close }} threshold
          {% elif delta >= 0.5 %}
            Still high: delta {{ delta | round(1) }} ≥ 0.5 g/m³
          {% else %}
            Still high
          {% endif %}
        {% else %}
          UNKNOWN
        {% endif %}

      # Logging levels: NONE = no logs, DEBUG = actionable only, TRACE = all including NOOP
      log_debug: >-
        {% if log_level == 'TRACE' %}
          true
        {% elif log_level == 'DEBUG' and outcome != 'NOOP' %}
          true
        {% else %}
          false
        {% endif %}

      snapshot: >-
        window={{ 'open' if window_state == 'on' else 'closed' }},
        open_mins={{ time_open_mins | round(0) }},
        rh={{ rh_inside | round(0) }}%,
        abs_in={{ abs_inside | round(1) }},
        abs_out={{ abs_outside | round(1) }},
        delta={{ delta | round(1) }},
        temp={{ temp_inside | round(1) }},
        mins_since_announce={{ mins_since_last_announce | round(1) }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ log_debug }}"
        sequence:
          - action: logbook.log
            data:
              name: "{{ this.attributes.friendly_name }}"
              entity_id: "{{ this.entity_id }}"
              message: >
                {{ outcome }} ({{ outcome_reason }}) | {{ humidity_status }} | {{ snapshot }}

  - choose:
      # OPEN HINT (window closed, should open)
      - conditions:
          - condition: template
            value_template: "{{ sensors_ok }}"
          - condition: template
            value_template: "{{ window_state == 'off' }}"
          - condition: template
            value_template: "{{ is_shower_zone }}"
          - condition: template
            value_template: "{{ is_physics_good }}"
          - condition: template
            value_template: "{{ is_temp_safe }}"
          - condition: template
            value_template: "{{ mins_since_last_announce >= announce_interval_mins }}"
        sequence:
          - action: !input tts_script
            data:
              message: !input tts_message_open
              media_player: "{{ tts_media_player_in }}"
              language: "{{ tts_language_in }}"
              volume: "{{ tts_volume_in }}"

          # NEW: persist "last spoken" time
          - action: input_datetime.set_datetime
            target:
              entity_id: !input last_tts_helper
            data:
              timestamp: "{{ now().timestamp() }}"

      # CLOSE HINT (window open, can/should close)
      - conditions:
          - condition: template
            value_template: "{{ sensors_ok }}"
          - condition: template
            value_template: "{{ window_state == 'on' }}"
          - condition: template
            value_template: "{{ mins_since_last_announce >= announce_interval_mins }}"
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ temp_inside < min_temp }}"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ time_open_mins >= min_open_time }}"
                  - condition: or
                    conditions:
                      - condition: template
                        value_template: "{{ rh_inside <= thresh_rh_close }}"
                      - condition: template
                        value_template: "{{ abs_inside <= thresh_abs_close }}"
                      - condition: template
                        value_template: "{{ delta < 0.5 }}"
        sequence:
          - action: !input tts_script
            data:
              message: >-
                {% if temp_inside < min_temp %}
                  {{ tts_message_close_cold }}
                {% else %}
                  {{ tts_message_close_normal }}
                {% endif %}
              media_player: "{{ tts_media_player_in }}"
              language: "{{ tts_language_in }}"
              volume: "{{ tts_volume_in }}"

          # NEW: persist "last spoken" time
          - action: input_datetime.set_datetime
            target:
              entity_id: !input last_tts_helper
            data:
              timestamp: "{{ now().timestamp() }}"

mode: single
