blueprint:
  name: Door/Window open-close, climate control
  description: >
    Turns off one or more climate devices when any selected window/door is open,
    and restores them when all are closed. Includes a 2.5-minute safety check.
  domain: automation

  input:
    room_windows:
      name: Windows/doors for this room
      description: One or more binary_sensors (window/door) in this room.
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - window
            - door
          multiple: true

    room_climate:
      name: Climate entities for this room
      description: One or more climate entities for this room.
      selector:
        entity:
          domain: climate
          multiple: true

    minimum_open_time:
      name: Minimum open time before turning off climate
      description: Time in seconds the windows must stay open.
      default: 30
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
          step: 1
          mode: slider

triggers:
  # Any window changes state
  - trigger: state
    id: window_state_change
    entity_id: !input room_windows

  # Safety timer every 2.5 minutes
  - trigger: time_pattern
    id: safety_tick
    minutes: "/2"

actions:
  - variables:
      win_entities: !input room_windows

      any_open: >
        {{ expand(win_entities) | selectattr('state','eq','on') | list | count > 0 }}

      all_closed: >
        {{ expand(win_entities) | selectattr('state','ne','on') | list | count == (expand(win_entities) | list | count) }}

  - choose:
      # Handle real-time window changes
      - conditions:
          - condition: trigger
            id: window_state_change
        sequence:
          - choose:
              # A window just opened (at least one open)
              - conditions:
                  - condition: template
                    value_template: "{{ any_open }}"
                sequence:
                  # Wait for min time or until all windows closed again
                  - wait_for_trigger:
                      - platform: state
                        entity_id: !input room_windows
                    timeout: !input minimum_open_time
                    continue_on_timeout: true

                  # Recompute window state after wait
                  - variables:
                      any_open_after: >
                        {{ expand(win_entities) | selectattr('state','eq','on') | list | count > 0 }}

                  # Only turn off climate if still at least one open
                  - condition: template
                    value_template: "{{ any_open_after }}"

                  - action: climate.turn_off
                    target:
                      entity_id: !input room_climate

              # All windows now closed
              - conditions:
                  - condition: template
                    value_template: "{{ all_closed }}"
                sequence:
                  - action: climate.turn_on
                    target:
                      entity_id: !input room_climate

                  - action: climate.set_hvac_mode
                    target:
                      entity_id: !input room_climate
                    data:
                      hvac_mode: auto

      # Safety tick: enforce correct state
      - conditions:
          - condition: trigger
            id: safety_tick
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ any_open }}"
                sequence:
                  - action: climate.turn_off
                    target:
                      entity_id: !input room_climate

              - conditions:
                  - condition: template
                    value_template: "{{ all_closed }}"
                sequence:
                  - action: climate.turn_on
                    target:
                      entity_id: !input room_climate
                  - action: climate.set_hvac_mode
                    target:
                      entity_id: !input room_climate
