blueprint:
  name: Tado Heating Override Detector
  description: >
    Watches Overlay sensors for selected Tado climates.
    When Overlay = 'on': stores temperature in input_number helper.
    When Overlay = 'off': sets temp to -1.
  domain: automation

  input:
    overlay_sensors:
      name: Tado overlay binary sensors
      description: Select all binary_sensor.*_overlay entities.
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    debug_mode:
      name: Enable debug logging
      description: Log detailed information to the logbook.
      default: false
      selector:
        boolean: {}

variables:
  debug_enabled: !input debug_mode

trigger:
  - trigger: state
    entity_id: !input overlay_sensors

conditions:
  - condition: template
    value_template: >
      {{ trigger is defined 
         and trigger.entity_id is not none 
         and trigger.entity_id != '' }}

action:
  - variables:
      overlay_sensor: "{{ trigger.entity_id }}"
      object_id: "{{ overlay_sensor.split('.')[1].replace('_overlay', '') }}"
      triggered_climate: "{{ 'climate.' ~ object_id }}"
      override_temp: "{{ 'input_number.climate_' ~ object_id ~ '_override_temp' }}"

      overlay_state: "{{ trigger.to_state.state | lower }}"
      hvac_mode: "{{ states(triggered_climate) }}"
      current_temp: "{{ state_attr(triggered_climate, 'temperature') | float(-1) }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ debug_enabled }}"
        sequence:
          - action: logbook.log
            data:
              name: "Tado Override Detector"
              entity_id: "{{ this.entity_id }}"
              message: >
                Triggered by {{ overlay_sensor }}. State: {{ overlay_state }}.
                Climate: {{ triggered_climate }} (mode: {{ hvac_mode }}, temp: {{ current_temp }}°C).
                Helper: {{ override_temp }}.

  - choose:
      # Overlay On + climate not off → store override temp
      - conditions:
          - condition: template
            value_template: >
              {{ overlay_state == 'on'
                 and hvac_mode not in ['off','unavailable','unknown'] }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ debug_enabled }}"
                sequence:
                  - action: logbook.log
                    data:
                      name: "Tado Override Detector"
                      entity_id: "{{ this.entity_id }}"
                      message: >
                        Manual override detected → storing {{ current_temp }}°C in {{ override_temp }}

          - action: input_number.set_value
            target:
              entity_id: "{{ override_temp }}"
            data:
              value: "{{ current_temp }}"

      # Overlay Off or climate off → clear override (set to -1)
      - conditions:
          - condition: template
            value_template: >
              {{ overlay_state == 'off' or hvac_mode == 'off' }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ debug_enabled }}"
                sequence:
                  - action: logbook.log
                    data:
                      name: "Tado Override Detector"
                      entity_id: "{{ this.entity_id }}"
                      message: >
                        Schedule active/off → clearing {{ override_temp }} to -1

          - action: input_number.set_value
            target:
              entity_id: "{{ override_temp }}"
            data:
              value: -1

mode: restart
