blueprint:
  name: Tado heating override detector
  description: >
    For each selected Tado climate, watches its Overlay sensor.
    If Overlay != 'Off' and hvac_mode != 'off', turns on
    input_boolean.<climate_entity>_override.
  domain: automation

  input:
    climates:
      name: Tado climate entities
      selector:
        entity:
          domain: climate
          multiple: true

triggers:
  - trigger: state
    entity_id: !input climates

actions:
  - variables:
      cl: "{{ trigger.entity_id }}"
      # Expected overlay sensor: sensor.<climate_object_id>_overlay
      object_id: "{{ cl.split('.')[1] }}"
      overlay_sensor: "{{ 'sensor.' ~ object_id ~ '_overlay' }}"
      override_bool: "{{ 'input_boolean.' ~ cl.replace('.', '_') ~ '_override' }}"

      new_climate: "{{ trigger.to_state }}"
      hvac_mode: "{{ new_climate.state if new_climate is not none else 'unknown' }}"
      overlay_state: "{{ states(overlay_sensor) | lower }}"

  - choose:
      # Turn ON override when overlay is active and climate not off
      - conditions:
          - condition: template
            value_template: >
              {{ overlay_state not in ['off','unknown','unavailable']
                 and hvac_mode not in ['off','unavailable','unknown'] }}
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: "{{ override_bool }}"

      # Optional: clear override when turned fully off or overlay cleared
      - conditions:
          - condition: template
            value_template: >
              {{ hvac_mode == 'off' or overlay_state in ['off','unknown','unavailable'] }}
        sequence:
          - action: input_boolean.turn_off
            target:
              entity_id: "{{ override_bool }}"

mode: restart
