blueprint:
  name: TTS Speak Helper with Volume Restore
  description: >
    Reusable script for TTS announcements with volume restore.
    Pass 'message' when calling; optionally override language, media_player, volume.
  domain: script

  input:
    default_media_player:
      name: Default media player
      default: media_player.homepod
      selector:
        entity:
          domain: media_player

    default_tts_service:
      name: Default TTS service
      default: tts.google_cloud
      selector:
        entity:
          domain: tts

    default_language:
      name: Default language
      default: de-DE
      selector:
        text: {}

    default_tts_volume:
      name: Default TTS volume
      default: 0.7
      selector:
        number:
          min: 0
          max: 1
          step: 0.05

    default_restore_volume:
      name: Fallback restore volume
      default: 0.6
      selector:
        number:
          min: 0
          max: 1
          step: 0.05

    wake_remote:
      name: Remote to wake speaker
      default: remote.homepod
      selector:
        entity:
          domain: remote

fields:
  message:
    description: The TTS message
    example: "Hello world"
  language:
    description: Language override
    example: en-US
  media_player:
    description: Media player override
    example: media_player.homepod
  volume:
    description: TTS volume override
    example: 0.8

sequence:
  - variables:
      input_media_player: !input default_media_player
      input_tts_service: !input default_tts_service
      input_language: !input default_language
      input_tts_volume: !input default_tts_volume
      input_restore_volume: !input default_restore_volume

      msg: "{{ message | default('') }}"
      lang: "{{ language | default(input_language) }}"
      player: "{{ media_player | default(input_media_player) }}"
      vol: "{{ (volume if volume is defined else input_tts_volume) | float }}"
      svc: "{{ input_tts_service }}"
      restore_vol: >-
        {{ state_attr(player, 'volume_level')
           | default(input_restore_volume)
           | float(input_restore_volume) }}

  - if:
      - condition: template
        value_template: "{{ msg | trim != '' }}"
    then:
      - action: remote.turn_on
        target:
          entity_id: !input wake_remote

      - action: media_player.volume_set
        target:
          entity_id: "{{ player }}"
        data:
          volume_level: "{{ vol }}"

      - action: tts.speak
        target:
          entity_id: "{{ svc }}"
        data:
          cache: true
          media_player_entity_id: "{{ player }}"
          message: "{{ msg }}"
          language: "{{ lang }}"

      - action: media_player.volume_set
        target:
          entity_id: "{{ player }}"
        data:
          volume_level: "{{ restore_vol }}"

mode: single
