blueprint:
  name: Door/Window open-close, climate control
  description: Turns off the climate device when a door/window is open and turns it back on when closed.
  domain: automation
  input:
    door_window_entity:
      name: Door/Window Sensor
      description: The window or door sensor controlling the climate device.
      selector:
        entity:
          domain: binary_sensor
          device_class: 
          - window
          - door
    climate_target:
      name: Climate Device
      description: The climate entity to control.
      selector:
        entity:
          domain: climate
    minimum_open_time:
      name: Minimum time to wait before turning off climate
      description: Time in seconds to wait after the window is opened.
      default: 30
      selector:
        number:
          min: 0.0
          max: 120.0
          unit_of_measurement: seconds
          mode: slider
          step: 1.0
trigger:
  - id: "window_opened"
    platform: state
    entity_id: !input 'door_window_entity'
    from: 'off'
    to: 'on'

  - id: "window_closed"
    platform: state
    entity_id: !input 'door_window_entity'
    from: 'on'
    to: 'off'
action:
  - choose:
      # If the window was opened
      - conditions:
          - condition: trigger
            id: "window_opened"
        sequence:
          # Wait for the minimum time OR for the window to close
          - wait_for_trigger:
              - platform: state
                entity_id: !input 'door_window_entity'
                to: 'off'  # Window closed
            timeout: !input 'minimum_open_time'
            continue_on_timeout: true
          # Check if the window is still open after the wait
          - condition: state
            entity_id: !input 'door_window_entity'
            state: 'on'
          # Turn off the climate device if the window is still open
          - service: climate.turn_off
            entity_id: !input 'climate_target'

      # If the window was closed
      - conditions:
          - condition: trigger
            id: "window_closed"
        sequence:
          # Turn the climate device back on immediately
          - service: climate.turn_on
            entity_id: !input 'climate_target'
          # Optional: Restore to "auto" mode for Tado users
          - service: climate.set_hvac_mode
            target:
              entity_id: !input 'climate_target'
            data:
              hvac_mode: auto
